### ISSUE TITLE
Planning to implement this?

### ISSUE THREAD

**Issue by malte-v** [RedisGraph/redisgraph-rs#2]
I'm interested in using RedisGraph with Rust. Are you planning to implement this in the near future? I'm willing to help out if you point me in the right direction.

**Comment by gkorland** [comment]
@malte-v I'm sorry but it doesn't seem like we'll get to implement it in the near future.
If you're willing to help that will be great! 
You can find here a list of RedisGraph clients you can use as reference.
https://oss.redislabs.com/redisgraph/clients/

If you have any questions will be happy to help.

**Comment by malte-v** [comment]
No worries, I'm currently working on this. I'll let you know when it's finished.

**Comment by malte-v** [comment]
FYI, here is my implementation of a RedisGraph client for Rust: https://github.com/malte-v/redisgraph-rs
You may want to add a link to that repo in case someone wants to use this.

**Comment by gkorland** [comment]
@malte-v Thanks!!! now I can close this repo :)
